language: minimal

git:
  depth: 1

branches:
  only:
  - master

install:
  - sudo apt-get install -y zip m4 recode gawk

before_script:
  - git clone --depth 1 https://github.com/laszlonemeth/magyarispell.git
  - cd magyarispell
  - export ISPELL_COMMIT_HASH=$(git log -1 --pretty=format:%h)
  - export ISPELL_COMMIT_DATE=$(git log -1 --pretty=format:%ad --date=format:%Y.%m.%d.%H.%M)
  - export EXTENSION_VERSION=${ISPELL_COMMIT_DATE}
  - export EXTENSION_FILE_NAME=hungarian_dictionary-${EXTENSION_VERSION}.xpi
  - export MAGYARISPELL_FILE_NAME=MagyarIspell_${ISPELL_COMMIT_HASH}.zip
  - make
  - cd ..

script:
  - export PATH=$(pwd)/tools:$PATH
  - chmod +x tools/mo
  - mkdir output
  - bash ./scripts/create_ispell_archive.sh magyarispell/ output/${MAGYARISPELL_FILE_NAME}
  - bash ./scripts/create_mozilla_dictionary.sh magyarispell/ templates/install.rdf.mustache output/${EXTENSION_FILE_NAME}
  - mkdir -p output/website
  - bash ./scripts/create_website.sh templates/ output/website/
  - git tag "${EXTENSION_VERSION}"

deploy:
  - provider: releases
    api_key: ${GH_TOKEN}
    file:
      - output/${EXTENSION_FILE_NAME}
      - output/${MAGYARISPELL_FILE_NAME}
    skip_cleanup: true
    body: "Generated from Magyar Ispell https://github.com/laszlonemeth/magyarispell (commit hash: ${ISPELL_COMMIT_HASH})"
  - provider: pages
    skip-cleanup: true
    github-token: ${GH_TOKEN}
    local-dir: output/website
